// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Link struct {
	ID          int64
	OriginalUrl string
	ShortName   string
	CreatedAt   pgtype.Timestamptz
}

type LinkVisit struct {
	ID        int64
	LinkID    int64
	Ip        string
	UserAgent string
	Referer   string
	Status    int32
	CreatedAt pgtype.Timestamptz
}
